---
- name: Install HTTP Server
  hosts: n2
  become: yes
  tasks:
    - name: Install HTTPD
      yum:
        name: httpd
        state: present  

- name: start httpd
  service: 
    name: httpd
    states: started

- name: Enable httpd
  service: 
    name: httpd
    enable: yes 
...
