---
- name: Deploy web app
  hosts: n2
  become: yes
  tasks:
    - name: Install Git
      yum:
        name: git
        state: present  

- name: Host Code
  git: 
    repo: https://github.com/damianpaintsil/food3.git
    dest: /var/www/html
...
