---
- name: Install HTTP Server
  hosts: g1
  become: yes

  tasks:
    - name: Install HTTPD on Amazon Linux
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "Amazon"

    - name: Start httpd on Amazon Linux
      service:
        name: httpd
        state: started
      when: ansible_distribution == "Amazon"

    - name: Enable httpd on Amazon Linux
      service:
        name: httpd
        enabled: yes
      when: ansible_distribution == "Amazon"

    - name: Install Apache2 on Ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Start Apache2 on Ubuntu
      service:
        name: apache2
        state: started
      when: ansible_distribution == "Ubuntu"

    - name: Enable Apache2 on Ubuntu
      service:
        name: apache2
        enabled: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache2 on Debian
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Debian"

    - name: Start Apache2 on Debian
      service:
        name: apache2
        state: started
      when: ansible_distribution == "Debian"

    - name: Enable Apache2 on Debian
      service:
        name: apache2
        enabled: yes
      when: ansible_distribution == "Debian"

    - name: Install httpd on CentOS
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "CentOS"

    - name: Start httpd on CentOS
      service:
        name: httpd
        state: started
      when: ansible_distribution == "CentOS"

    - name: Enable httpd on CentOS
      service:
        name: httpd
        enabled: yes
      when: ansible_distribution == "CentOS"
