---
- name: Install Apache on web servers
  hosts: webservers
  become: yes
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

- name: Install MySQL on db servers
  hosts: dbservers
  become: yes
  tasks:
    - name: Install MySQL
      yum:
        name: mariadb-server
        state: present      
...
